---
title: "Logistic regression in R"
author: "Krishna P Koirala"
date: "6/5/2018"
output:
    md_document:
     variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
adult <- read.csv('adult_sal.csv')
```

```{r}
head(adult)
```



```{r}
library(dplyr)
adult <- select(adult, -X)
```

```{r}
str(adult)
```


```{r}
summary(adult)
```



```{r}
table(adult$type_employer)
```


# Feature engineering/Data Cleaning

```{r}
# combine employer type
unemp <- function(job){
    job <- as.character(job)
    if(job=='Never-worked' | job == 'Without-pay'){
        return('Unemployed')
    }else{
        return(job)
    }
    
}
```

```{r}
adult$type_employer <- sapply(adult$type_employer, unemp)
table(adult$type_employer)
```

```{r}
# Group self employed
group_emp <- function(job){
    if(job =='Local-gov' | job == 'State-gov'){
        return('SL-gov')
    }else if (job=='Self-emp-inc' | job=='Self-emp-not-inc'){
        return('self-emp')
    }else{
        return(job)
    }
}
```

```{r}
adult$type_employer <- sapply(adult$type_employer, group_emp)
```


```{r}
table(adult$marital)
```


```{r}
# Marital status
group_marital <- function(mar){
    mar <- as.character(mar)
    
    # not married
    if(mar=='Separated' | mar == 'Divorced' | mar == 'Widowed'){
        return('Not-Married')
        
        #Never married
    }else if(mar == 'Never-married'){
        return(mar)
        
        # Married
        
    }else{
        return('Married')
    }
}
```

```{r}
adult$marital <- sapply(adult$marital, group_marital)
table(adult$marital)
```


```{r}
#colnames(adult)
table(adult$country)
```



```{r}
# Grouping country column 
Asia <- c('China','Hong','India','Iran','Cambodia','Japan', 'Laos' ,
          'Philippines' ,'Vietnam' ,'Taiwan', 'Thailand')

North.America <- c('Canada','United-States','Puerto-Rico' )

Europe <- c('England' ,'France', 'Germany' ,'Greece','Holand-Netherlands','Hungary',
            'Ireland','Italy','Poland','Portugal','Scotland','Yugoslavia')

Latin.and.South.America <- c('Columbia','Cuba','Dominican-Republic','Ecuador',
                             'El-Salvador','Guatemala','Haiti','Honduras',
                             'Mexico','Nicaragua','Outlying-US(Guam-USVI-etc)','Peru',
                            'Jamaica','Trinadad&Tobago')
Other <- c('South')
```



```{r}
group_country <- function(ctry){
    if(ctry %in% Asia){
        return('Asia')
    }else if(ctry %in% North.America){
        return('North.America')
    }else if(ctry %in% Europe){
        return('Europe')
    }else if(ctry %in% Latin.and.South.America){
        return('Latin.and.South.America')
    }else{
        return('Other')
    }
}
```


```{r}
# Using sapply here. The syntex of sapply is.
# sapply(object, function, ...) where object = list or df or vector
adult$country <- sapply(adult$country, group_country)
```

```{r}
table(adult$country)
```

### changing data type of newly created columns

```{r}
#str(adult)
adult$type_employer <- as.factor(adult$type_employer)
adult$country <- sapply(adult$country, factor)
adult$marital <- sapply(adult$marital, factor)
```

```{r}
str(adult)
```


## Dealing with missing values

```{r}
# Change ? to NA and drop those NAs
adult[adult == '?'] <- NA
```


```{r}
# check the presence of NAs
table(is.na(adult))
```

```{r}
# Now drom those NAs
adult <- na.omit(adult)
table(is.na(adult))
# all NAs are gone
```

# Visualization

```{r}
library(ggplot2)
ggplot(aes(age), data = adult) + geom_histogram(aes(fill = income), color = 'black', binwidth = 1) + theme_bw()
```

```{r}
colnames(adult)
ggplot(aes(hr_per_week), data = adult) + geom_histogram()
```

```{r}
# Changing the name of country column to Region
# data <- rename(data, new_col_name = old_col_name)
adult <- rename(adult, region = country)
#colnames(adult)
```


```{r}
ggplot(aes(region), data = adult) + geom_bar(aes(fill = income), color = 'black') + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


# Logistic regression

```{r}
str(adult)
```

# Split 

```{r}
library(caret)
set.seed(101)
trainIndex <- createDataPartition(adult$income, p = 0.7, list = FALSE,times = 1)
adult_train <- adult[trainIndex,]
adult_test <- adult[-trainIndex,]

#library(caTools)
#set.seed(101)
#sample <- sample.split(adult$income, SplitRatio = 0.7)
#train <- subset(adult, sample == T)
#test <- subset(adult, sample == F)
```


```{r}
model <- glm(income ~., family = binomial(link = 'logit'), data = adult_train)
summary(model)
```


```{r}
# Using step aic method for best variable selection
library(MASS)
# Perform stepwise model selection
step <- stepAIC(model, direction = "both")
```

```{r}
step$anova
```


```{r}
# Now I am gonna use my final variables to make new model
model_final <- glm(income ~ age + type_employer + fnlwgt + education + marital + 
    occupation + relationship + race + sex + capital_gain + capital_loss + 
    hr_per_week + region, family = binomial(link = 'logit'), data = adult_train)
summary(model_final)
```



The model_final became our final model

# Prediction

```{r}
adult_test$predicted.income <- predict(model_final, newdata = adult_test, type = 'response')
```


# Confusion matrix

```{r}
table(adult_test$income, adult_test$predicted.income >0.5)
```

# Accuracy of the model
```{r}
acc <- (6423+1355)/(6423+1355+940+497)
acc # Our model is 84.4% accurate to predict the income
```


```{r}
# Recall
rec <- 6423/(6423+497)
rec
```

```{r}
# Precision
prec <- 6423/(6423+940)
prec
```

